name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true

      - name: Install dependencies
        run: go get .
         
      - name: Build
        run: ./build-all.sh

      - name: Upload Binaries (Linux)
        uses: actions/upload-artifact@v3
        with:
          name: launcvc_linux_bin
          path: ./bin/launcvc_linux*
          if-no-files-found: error

      - name: Upload Binaries (macOS)
        uses: actions/upload-artifact@v3
        with:
          name: launcvc_darwin_bin
          path: ./bin/launcvc_darwin*
          if-no-files-found: error

      - name: Upload Binaries (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: launcvc_windows_bin
          path: ./bin/launcvc_win*
          if-no-files-found: error